name: Deploy NodeJS Application on VM 
on:
  push:
    branches:
      - master

jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: deploy via SSH
         uses: appleboy/ssh-action@v0.1.5
         with:
           host: ${{ secrets.SSH_HOST }}
           username: root
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd /home/sam/nodejs-app-deploy-github-actions
             docker compose up -d --build